use_frameworks!

platform :ios, '9.0'

target 'Example' do
  pod 'CaamDauExtensionObjC', :path => '../'
  
  #pod 'Home', :path => './Module/Home'

  #target 'Example' do
  #  inherit! :search_paths

  #  pod 'Kiwi'
    #pod 'FBSnapshotTestCase'
  #end
end
